In [42]:
#for loops
my_list= [1,2,3,4]
my_list
#for executing each element
n=len(my_list)
for i in range(0,4):
    print(my_list[i])

1
2
3
4


In [46]:
#To stop a loop at a particular value, 3:
my_list
for i in my_list:
    if i==2:
        break
        print(i)
    
    




In [47]:
#To stop the loop at a particular value but to continue to the next value:
my_list
for y in my_list:
    if y==2:
        continue
        print(y)

In [50]:
#Convert list into a set:
list_1= [1,2,3,4,5,6,56,6,6]
set1= set(list_1)
set1

{1, 2, 3, 4, 5, 6, 56}

In [51]:
len(set1)

7

In [67]:
dist= [100,200,300,400]
time= [1,2,2.3,5]
import numpy as np

dist= np.array(dist)
dist
time= np.array(time)
time
vel= dist/time
vel

array([100.        , 100.        , 130.43478261,  80.        ])

In [74]:
dist= [100,200,300,400]
time= [1,2,2.3,5]
velocity=[]
for i in range(0,4):
    vel= dist[i]/time[i]
    velocity.append(vel)
print(velocity)

    

[100.0, 100.0, 130.43478260869566, 80.0]


In [75]:
for i in range(0,4):
    print(i)

0
1
2
3


In [77]:
#using range function with a step of 2:
for i in range(0,8,2):
    print(i)

0
2
4
6


In [93]:
list1= range(0,10000000)
list1

range(0, 10000000)

In [94]:
#calculating the time it takes to execute the operation for a list:
%%timeit
sum(list1)

UsageError: Line magic function `%%timeit` not found.


In [90]:
array1=np.array(list1) 
array1

array([      0,       1,       2, ..., 9999997, 9999998, 9999999])

In [92]:
%%timeit
sum(array1)

3.59 s ± 128 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


<magic-timeit>:1: RuntimeWarning: overflow encountered in long_scalars


In [107]:
array1= np.array([10,20,30])
array1

array([10, 20, 30])

In [108]:
type.array1

AttributeError: type object 'type' has no attribute 'array1'

In [109]:
type(array1)

numpy.ndarray

In [111]:
array1.size

3

In [113]:
array1.ndim

1

In [114]:
array1.shape

(3,)

In [117]:
two_d=np.array([[1,2,3],[4,5,6]])
two_d

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
two_d.size

6

In [119]:
two_d.ndim

2

In [120]:
two_d.shape

(2, 3)

In [123]:
#getting the first index
two_d[0][0]

1

In [124]:
two_d[1][2]

6

In [125]:
array1

array([10, 20, 30])

In [126]:
array1[2]

30

In [128]:
two_d[1][1]

5

In [130]:
my_2d= np.array([[1,2,3,4],[5,5,6,7],[100,200,300,499]])
my_2d

array([[  1,   2,   3,   4],
       [  5,   5,   6,   7],
       [100, 200, 300, 499]])

In [131]:
my_2d.shape

(3, 4)

In [132]:
my_2d[2][3]

499

In [133]:
np.arange(0,24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [134]:
np.arange(0,24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [138]:
my_3d= np.arange(0,24).reshape(4,3,2)
my_3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [139]:
my_3d[3][2][1]

23

In [140]:
my_3d[1][2][1]

11

In [141]:
my_3d[3][2][0]

22

In [144]:
#To access two elements together: 11,22
my_3d[[1,3],[2,2],[1,0]]

array([11, 22])

In [145]:
my_3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [146]:
#To access three elements:9,14,19
my_3d[[1,2,3],[1,1,0],[1,0,1]]

array([ 9, 14, 19])

In [147]:
my_3d>10

array([[[False, False],
        [False, False],
        [False, False]],

       [[False, False],
        [False, False],
        [False,  True]],

       [[ True,  True],
        [ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True],
        [ True,  True]]])

In [148]:
my_3d[my_3d>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [150]:
arr1=np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [151]:
arr1.dtype

dtype('int32')

In [152]:
arr1= np.array([1,2,3,4.2])

In [153]:
print(arr1)

[1.  2.  3.  4.2]


In [161]:
arr1=np.array([1,2,True])
arr1.dtype

dtype('int32')

In [154]:
arr1.dtype

dtype('float64')

In [155]:
arr1= np.array([1,2,3.3,True])

In [157]:
arr1.dtype

dtype('float64')

In [158]:
arr1= np.array([1,2,3.4,'d',True])

In [159]:
arr1.dtype

dtype('<U32')

# Hierarchy of typecasting:
Boolean<Integer<Float<String

In [4]:
np_linspace= np.linspace(1,6,5)
np_linspace

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [2]:
import numpy as np

In [9]:
np_lin= np.linspace(1,100,51)

In [10]:
np_lin

array([  1.  ,   2.98,   4.96,   6.94,   8.92,  10.9 ,  12.88,  14.86,
        16.84,  18.82,  20.8 ,  22.78,  24.76,  26.74,  28.72,  30.7 ,
        32.68,  34.66,  36.64,  38.62,  40.6 ,  42.58,  44.56,  46.54,
        48.52,  50.5 ,  52.48,  54.46,  56.44,  58.42,  60.4 ,  62.38,
        64.36,  66.34,  68.32,  70.3 ,  72.28,  74.26,  76.24,  78.22,
        80.2 ,  82.18,  84.16,  86.14,  88.12,  90.1 ,  92.08,  94.06,
        96.04,  98.02, 100.  ])

In [12]:
np_linspce= np.linspace(1,60,20)
np_linspce

array([ 1.        ,  4.10526316,  7.21052632, 10.31578947, 13.42105263,
       16.52631579, 19.63157895, 22.73684211, 25.84210526, 28.94736842,
       32.05263158, 35.15789474, 38.26315789, 41.36842105, 44.47368421,
       47.57894737, 50.68421053, 53.78947368, 56.89473684, 60.        ])

In [31]:
one_dim_array= np.arange(1,21).reshape(4,5)
one_dim_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [30]:
two_dim_array= np.array([[1,2,3,4],[4,5,6,7]])
two_dim_array

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [33]:
two_array= one_dim_array.reshape(2,2,5)
two_array

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [35]:
three_dim= np.arange(1,28).reshape(3,3,3)
three_dim

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [36]:
#addition in array:
np.add(45,23)

68

In [38]:
#Substraction in array:
np.subtract(45,23)

22

In [40]:
np_daily_wage= np.array([12,23,5,2,7,6])*15
np_daily_wage

array([180, 345,  75,  30, 105,  90])

In [41]:
np.sum(np_daily_wage)

825

In [43]:
np_daily_wage[np_daily_wage>105]

array([180, 345])

In [45]:
np_daily_wage[np_daily_wage!=30]

array([180, 345,  75, 105,  90])

In [48]:
##### Using Logical Operations:
#And Operation:
np_daily_wage[np.logical_and(np_daily_wage>75, np_daily_wage<345)]


array([180, 105,  90])

In [51]:
#OR Operation:
np_daily_wage[np.logical_or(np_daily_wage<75,np_daily_wage<105)]

array([75, 30, 90])

In [52]:
three_dim

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [55]:
three_dim[2][1][0]

22

In [60]:
three_dim[2,:,1:3]

array([[20, 21],
       [23, 24],
       [26, 27]])

In [63]:
np_sqrt= np.sqrt([4,9,25,64])
np_sqrt
np_sqrt.dtype

dtype('float64')

In [71]:
import numpy as np
a= np.pi
np.cos(a)

-1.0

In [73]:
a= np.pi/2
np.sin(a)

1.0

In [74]:
np.cos(np.pi/2)

6.123233995736766e-17

In [76]:
np.floor([1.3,4.5,7.8,6.7])

array([1., 4., 7., 6.])

In [78]:
np.exp([2,3,4])

array([ 7.3890561 , 20.08553692, 54.59815003])

In [79]:
three_dim

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [80]:
three_dim.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [84]:
three_dim.reshape(3,9)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [98]:
np.transpose(three_dim)

array([[[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]],

       [[ 3, 12, 21],
        [ 6, 15, 24],
        [ 9, 18, 27]]])