# Single integration

In [27]:
#Integration using sciPy:
from scipy.integrate import quad
#Defining the function, x:
def integrate_func(x):
    return(x)

In [29]:
#Giving the limits of the integration:
quad(integrate_func,0,1)

(0.5, 5.551115123125783e-15)

In [33]:
#Integration of the function, ax+b:
from scipy.integrate import quad
def integrate_func(x):
        return(a*x+b)

In [36]:
#Giving the values of constants a,b:
a= 2
b=6
#Giving the limits of integration:
quad(integrate_func, 0,1)

(7.0, 7.771561172376096e-14)

# Double Integration

In [53]:
import scipy.integrate as integrate
def double_integrate_func(x,y):
    return(x*y)

In [57]:
#here x ranges from 0 to 1 and y ranges from 1 to 5, lambda gives the range of y
integrate.dblquad(double_integrate_func,0,1, lambda x:1, lambda x:5)

(6.0, 1.329374718989623e-13)

In [55]:
#Double integration:
import scipy.integrate as integrate
def double_integration_fn(x,y):
    return(x*2+y*2)

In [56]:
#here x ranges from 0 to 1 and y ranges from 1 to 3, lambda gives the range of y
integrate.dblquad(double_integration_fn, 1,4, lambda x:1, lambda x:3)

(53.999999999999986, 5.995204332975843e-13)

# Optimization

In [69]:
#Optimise using scipy
#Importing the relevant libraries:
import numpy as np
import scipy.optimize as opt

In [73]:
#Defining the function, x^3+exp(x):
def opt_func(x):
    return(x**3+np.exp(x))


In [76]:
opt.minimize(opt_func,x0=0,method='bfgs',options={'disp':True})

         Current function value: -1073741824.000000
         Iterations: 1
         Function evaluations: 236
         Gradient evaluations: 112


      fun: array([-1.07374182e+09])
 hess_inv: array([[-0.00032552]])
      jac: array([3145728.])
  message: 'Desired error not necessarily achieved due to precision loss.'
     nfev: 236
      nit: 1
     njev: 112
   status: 2
  success: False
        x: array([-1024.])

In [77]:
opt.minimize(opt_func, x0=2, method='bfgs')

      fun: array([-5.01575552e+08])
 hess_inv: array([[-0.00041944]])
      jac: array([1893848.])
  message: 'Desired error not necessarily achieved due to precision loss.'
     nfev: 244
      nit: 5
     njev: 116
   status: 2
  success: False
        x: array([-794.53332952])

In [78]:
#Defining another function, x^2+sin(x):
def opt_function(x):
    return(x**2+np.sin(x))

In [79]:
opt.minimize(opt_function, x0=6, method= 'bfgs', options={'disp':True})

Optimization terminated successfully.
         Current function value: -0.232466
         Iterations: 9
         Function evaluations: 20
         Gradient evaluations: 10


      fun: -0.23246557515821556
 hess_inv: array([[0.41057908]])
      jac: array([1.86264515e-09])
  message: 'Optimization terminated successfully.'
     nfev: 20
      nit: 9
     njev: 10
   status: 0
  success: True
        x: array([-0.45018362])

In [81]:
import numpy as np
from scipy.optimize import root

In [82]:
#defining the function, x+3.5cos(x):
def root_fn(x):
    return(x+ 3.5*(np.cos(x)))

In [83]:
root(root_fn, 0)

    fjac: array([[-1.]])
     fun: array([0.])
 message: 'The solution converged.'
    nfev: 9
     qtf: array([1.74660286e-12])
       r: array([-4.28198138])
  status: 1
 success: True
       x: array([-1.21597614])

# Linear Algebra Using Scipy

In [87]:
#Inverse of the matrix, note:the matrix should be a square matrix:
import numpy as np
import scipy.linalg 

In [90]:
#Taking a 3by3 matrix
mat=  np.array([[1,2,3],[4,5,6],[7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
scipy.linalg.inv(mat)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [92]:
#Finding the determinant of the matrix
scipy.linalg.det(mat)

0.0

In [93]:
#Solving linear equation:
#2x+4y+4z= 20, 3x+5y+z=2, 2x+y+z=14
mat_variables= np.array([[2,4,4],[3,5,1],[2,1,1]])
mat_variables

array([[2, 4, 4],
       [3, 5, 1],
       [2, 1, 1]])

In [94]:
mat_values= np.array([20,2,14])

In [95]:
scipy.linalg.solve(mat_variables,mat_values)

array([ 6. , -4.5,  6.5])

In [96]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
scipy.linalg.svd(mat)
#Three matrices formed on multiplication will give the original matrix,3 matrices formed are U,sigma,Vtranspose
#U and Vtranspose are unitary matrices.
#Sigma is coefficient matrix and like PCA this is also dimensionality reduction matrix, first coefficient carries maximum infor-
#-mation, then second and then third, so if the original matrix on which SVD is carried out is very big then few starting-
# coefficients can be considered and then by multiplying it with U and Vtranspose matrix we can get maximum information with -
# dimensionality reduction and some loss.

(array([[-0.21483724,  0.88723069,  0.40824829],
        [-0.52058739,  0.24964395, -0.81649658],
        [-0.82633754, -0.38794278,  0.40824829]]),
 array([1.68481034e+01, 1.06836951e+00, 3.33475287e-16]),
 array([[-0.47967118, -0.57236779, -0.66506441],
        [-0.77669099, -0.07568647,  0.62531805],
        [-0.40824829,  0.81649658, -0.40824829]]))

# Eigen Values and Eigen Vectors

In [1]:
import numpy as np
import scipy.linalg

In [4]:
#Printing the matrix:
mat= np.array([[3,4],[6,8]])
mat

array([[3, 4],
       [6, 8]])

In [15]:
#Eigen Values:
eigen_values, eigen_vectors=scipy.linalg.eig(mat)
print(eigen_values)
print(eigen_vectors)

[ 0.+0.j 11.+0.j]
[[-0.8        -0.4472136 ]
 [ 0.6        -0.89442719]]


In [13]:
#printing the eigen values:
first_eigen_value, second_eigen_value= eigen_values
print(first_eigen_value)
print(second_eigen_value)

0j
(11+0j)


In [16]:
#printing the first eigen vector:
eigen_vectors[:,0]

array([-0.8,  0.6])

In [17]:
#printing the second eigen vector:
eigen_vectors[:,1]

array([-0.4472136 , -0.89442719])

# Statistics

In [1]:
#importing the library:
from scipy.stats import norm

In [2]:
#generating 10 random values having mean(loc)=0, standard deviation(scale)=1
norm.rvs(loc=0, scale=1, size=10)

array([ 2.40435112,  0.27070534, -1.1923801 ,  1.47011763,  0.59023162,
        0.70102244,  0.89649136,  1.90455366,  0.02471632, -0.85653004])

In [5]:
#Cumulative distribution function of 10 random numbers, having mean(loc)=0, standard deviation(scale)=1.
norm.cdf(10,loc=0,scale=1)

1.0

In [6]:
#Cumulative distribution function of 10 random numbers, having mean(loc)=9, standard deviation(scale)=1.5
norm.cdf(10, loc=9, scale=1.5)

0.7475074624530771

In [7]:
#Probability distribution function of 10 random numbers, having mean(loc)=0, standard deviation(scale)=1.
norm.pdf(10, loc=0, scale=1)

7.69459862670642e-23

In [8]:
#Probability distribution function of 10 random numbers, having mean(loc)=9, standard deviation(scale)=1.5
norm.pdf(10, loc=9, scale=1.5)

0.2129653370149015

# Probability distribution function is a derivative of cumulative distribution function